# [START functions_ci_cd_cloud_build]
steps:
- name: 'docker.io/library/python:3.7'
  entrypoint: /bin/sh
  # Run pip install and pytest in the same build step
  # (pip packages won't be preserved in future steps!)
  args: [-c, 'pip install -r requirements.txt', '&&', 'pytest']
  dir: 'function/dir/from/repo/root/functions/tips'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'file_wide_computation', '--trigger-http', '--runtime', 'python37', '--entry-point', 'file_wide_computation']
  dir: 'function/dir/from/repo/root/functions/tips'
# [END functions_ci_cd_cloud_build]
